/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as DevelopRouteImport } from './routes/develop'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as PQuesterHandleRouteImport } from './routes/p/$questerHandle'
import { Route as LeaderboardsWeeklyRouteImport } from './routes/leaderboards.weekly'
import { Route as LeaderboardsDailyRouteImport } from './routes/leaderboards.daily'
import { Route as BBadgeSlugRouteImport } from './routes/b/$badgeSlug'
import { Route as PrivateDashboardRouteImport } from './routes/_private/dashboard'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopRoute = DevelopRouteImport.update({
  id: '/develop',
  path: '/develop',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PQuesterHandleRoute = PQuesterHandleRouteImport.update({
  id: '/p/$questerHandle',
  path: '/p/$questerHandle',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsWeeklyRoute = LeaderboardsWeeklyRouteImport.update({
  id: '/leaderboards/weekly',
  path: '/leaderboards/weekly',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsDailyRoute = LeaderboardsDailyRouteImport.update({
  id: '/leaderboards/daily',
  path: '/leaderboards/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const BBadgeSlugRoute = BBadgeSlugRouteImport.update({
  id: '/b/$badgeSlug',
  path: '/b/$badgeSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateDashboardRoute = PrivateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/develop': typeof DevelopRoute
  '/guide': typeof GuideRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/b/$badgeSlug': typeof BBadgeSlugRoute
  '/leaderboards/daily': typeof LeaderboardsDailyRoute
  '/leaderboards/weekly': typeof LeaderboardsWeeklyRoute
  '/p/$questerHandle': typeof PQuesterHandleRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/develop': typeof DevelopRoute
  '/guide': typeof GuideRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/b/$badgeSlug': typeof BBadgeSlugRoute
  '/leaderboards/daily': typeof LeaderboardsDailyRoute
  '/leaderboards/weekly': typeof LeaderboardsWeeklyRoute
  '/p/$questerHandle': typeof PQuesterHandleRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_private': typeof PrivateRouteRouteWithChildren
  '/develop': typeof DevelopRoute
  '/guide': typeof GuideRoute
  '/_private/dashboard': typeof PrivateDashboardRoute
  '/b/$badgeSlug': typeof BBadgeSlugRoute
  '/leaderboards/daily': typeof LeaderboardsDailyRoute
  '/leaderboards/weekly': typeof LeaderboardsWeeklyRoute
  '/p/$questerHandle': typeof PQuesterHandleRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/develop'
    | '/guide'
    | '/dashboard'
    | '/b/$badgeSlug'
    | '/leaderboards/daily'
    | '/leaderboards/weekly'
    | '/p/$questerHandle'
    | '/sign-in/$'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/develop'
    | '/guide'
    | '/dashboard'
    | '/b/$badgeSlug'
    | '/leaderboards/daily'
    | '/leaderboards/weekly'
    | '/p/$questerHandle'
    | '/sign-in/$'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/develop'
    | '/guide'
    | '/_private/dashboard'
    | '/b/$badgeSlug'
    | '/leaderboards/daily'
    | '/leaderboards/weekly'
    | '/p/$questerHandle'
    | '/sign-in/$'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  DevelopRoute: typeof DevelopRoute
  GuideRoute: typeof GuideRoute
  BBadgeSlugRoute: typeof BBadgeSlugRoute
  LeaderboardsDailyRoute: typeof LeaderboardsDailyRoute
  LeaderboardsWeeklyRoute: typeof LeaderboardsWeeklyRoute
  PQuesterHandleRoute: typeof PQuesterHandleRoute
  SignInSplatRoute: typeof SignInSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/develop': {
      id: '/develop'
      path: '/develop'
      fullPath: '/develop'
      preLoaderRoute: typeof DevelopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$questerHandle': {
      id: '/p/$questerHandle'
      path: '/p/$questerHandle'
      fullPath: '/p/$questerHandle'
      preLoaderRoute: typeof PQuesterHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards/weekly': {
      id: '/leaderboards/weekly'
      path: '/leaderboards/weekly'
      fullPath: '/leaderboards/weekly'
      preLoaderRoute: typeof LeaderboardsWeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards/daily': {
      id: '/leaderboards/daily'
      path: '/leaderboards/daily'
      fullPath: '/leaderboards/daily'
      preLoaderRoute: typeof LeaderboardsDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$badgeSlug': {
      id: '/b/$badgeSlug'
      path: '/b/$badgeSlug'
      fullPath: '/b/$badgeSlug'
      preLoaderRoute: typeof BBadgeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/dashboard': {
      id: '/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PrivateRouteRouteChildren {
  PrivateDashboardRoute: typeof PrivateDashboardRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateDashboardRoute: PrivateDashboardRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  DevelopRoute: DevelopRoute,
  GuideRoute: GuideRoute,
  BBadgeSlugRoute: BBadgeSlugRoute,
  LeaderboardsDailyRoute: LeaderboardsDailyRoute,
  LeaderboardsWeeklyRoute: LeaderboardsWeeklyRoute,
  PQuesterHandleRoute: PQuesterHandleRoute,
  SignInSplatRoute: SignInSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
