/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as PQuesterHandleRouteImport } from './routes/p/$questerHandle'
import { Route as LeaderboardsWeeklyRouteImport } from './routes/leaderboards.weekly'
import { Route as LeaderboardsDailyRouteImport } from './routes/leaderboards.daily'
import { Route as BBadgeSlugRouteImport } from './routes/b/$badgeSlug'

const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PQuesterHandleRoute = PQuesterHandleRouteImport.update({
  id: '/p/$questerHandle',
  path: '/p/$questerHandle',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsWeeklyRoute = LeaderboardsWeeklyRouteImport.update({
  id: '/leaderboards/weekly',
  path: '/leaderboards/weekly',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsDailyRoute = LeaderboardsDailyRouteImport.update({
  id: '/leaderboards/daily',
  path: '/leaderboards/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const BBadgeSlugRoute = BBadgeSlugRouteImport.update({
  id: '/b/$badgeSlug',
  path: '/b/$badgeSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/b/$badgeSlug': typeof BBadgeSlugRoute
  '/leaderboards/daily': typeof LeaderboardsDailyRoute
  '/leaderboards/weekly': typeof LeaderboardsWeeklyRoute
  '/p/$questerHandle': typeof PQuesterHandleRoute
  '/sign-in/$': typeof SignInSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/b/$badgeSlug': typeof BBadgeSlugRoute
  '/leaderboards/daily': typeof LeaderboardsDailyRoute
  '/leaderboards/weekly': typeof LeaderboardsWeeklyRoute
  '/p/$questerHandle': typeof PQuesterHandleRoute
  '/sign-in/$': typeof SignInSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/b/$badgeSlug': typeof BBadgeSlugRoute
  '/leaderboards/daily': typeof LeaderboardsDailyRoute
  '/leaderboards/weekly': typeof LeaderboardsWeeklyRoute
  '/p/$questerHandle': typeof PQuesterHandleRoute
  '/sign-in/$': typeof SignInSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guide'
    | '/b/$badgeSlug'
    | '/leaderboards/daily'
    | '/leaderboards/weekly'
    | '/p/$questerHandle'
    | '/sign-in/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guide'
    | '/b/$badgeSlug'
    | '/leaderboards/daily'
    | '/leaderboards/weekly'
    | '/p/$questerHandle'
    | '/sign-in/$'
  id:
    | '__root__'
    | '/'
    | '/guide'
    | '/b/$badgeSlug'
    | '/leaderboards/daily'
    | '/leaderboards/weekly'
    | '/p/$questerHandle'
    | '/sign-in/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuideRoute: typeof GuideRoute
  BBadgeSlugRoute: typeof BBadgeSlugRoute
  LeaderboardsDailyRoute: typeof LeaderboardsDailyRoute
  LeaderboardsWeeklyRoute: typeof LeaderboardsWeeklyRoute
  PQuesterHandleRoute: typeof PQuesterHandleRoute
  SignInSplatRoute: typeof SignInSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$questerHandle': {
      id: '/p/$questerHandle'
      path: '/p/$questerHandle'
      fullPath: '/p/$questerHandle'
      preLoaderRoute: typeof PQuesterHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards/weekly': {
      id: '/leaderboards/weekly'
      path: '/leaderboards/weekly'
      fullPath: '/leaderboards/weekly'
      preLoaderRoute: typeof LeaderboardsWeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards/daily': {
      id: '/leaderboards/daily'
      path: '/leaderboards/daily'
      fullPath: '/leaderboards/daily'
      preLoaderRoute: typeof LeaderboardsDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$badgeSlug': {
      id: '/b/$badgeSlug'
      path: '/b/$badgeSlug'
      fullPath: '/b/$badgeSlug'
      preLoaderRoute: typeof BBadgeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuideRoute: GuideRoute,
  BBadgeSlugRoute: BBadgeSlugRoute,
  LeaderboardsDailyRoute: LeaderboardsDailyRoute,
  LeaderboardsWeeklyRoute: LeaderboardsWeeklyRoute,
  PQuesterHandleRoute: PQuesterHandleRoute,
  SignInSplatRoute: SignInSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
