/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as PublicLeaderboardsWeeklyRouteImport } from './routes/_public/leaderboards.weekly'
import { Route as PublicLeaderboardsDailyRouteImport } from './routes/_public/leaderboards.daily'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLeaderboardsWeeklyRoute =
  PublicLeaderboardsWeeklyRouteImport.update({
    id: '/leaderboards/weekly',
    path: '/leaderboards/weekly',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicLeaderboardsDailyRoute = PublicLeaderboardsDailyRouteImport.update({
  id: '/leaderboards/daily',
  path: '/leaderboards/daily',
  getParentRoute: () => PublicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/leaderboards/daily': typeof PublicLeaderboardsDailyRoute
  '/leaderboards/weekly': typeof PublicLeaderboardsWeeklyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/leaderboards/daily': typeof PublicLeaderboardsDailyRoute
  '/leaderboards/weekly': typeof PublicLeaderboardsWeeklyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_public': typeof PublicRouteRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/_public/leaderboards/daily': typeof PublicLeaderboardsDailyRoute
  '/_public/leaderboards/weekly': typeof PublicLeaderboardsWeeklyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in/$' | '/leaderboards/daily' | '/leaderboards/weekly'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in/$' | '/leaderboards/daily' | '/leaderboards/weekly'
  id:
    | '__root__'
    | '/'
    | '/_public'
    | '/sign-in/$'
    | '/_public/leaderboards/daily'
    | '/_public/leaderboards/weekly'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/leaderboards/weekly': {
      id: '/_public/leaderboards/weekly'
      path: '/leaderboards/weekly'
      fullPath: '/leaderboards/weekly'
      preLoaderRoute: typeof PublicLeaderboardsWeeklyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/leaderboards/daily': {
      id: '/_public/leaderboards/daily'
      path: '/leaderboards/daily'
      fullPath: '/leaderboards/daily'
      preLoaderRoute: typeof PublicLeaderboardsDailyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicLeaderboardsDailyRoute: typeof PublicLeaderboardsDailyRoute
  PublicLeaderboardsWeeklyRoute: typeof PublicLeaderboardsWeeklyRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLeaderboardsDailyRoute: PublicLeaderboardsDailyRoute,
  PublicLeaderboardsWeeklyRoute: PublicLeaderboardsWeeklyRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
